# nginx.conf
events {}

# partially copied from:
# https://medium.com/@colinatjku/integrating-flask-and-react-using-vite-for-development-and-nginx-in-production-a-microservices-9df7a21ca8f5
http {
  server {
    listen 80;
    server_name localhost;
    # Primary rule for serving the Vite dev frontend
    location / {
      proxy_pass http://0.0.0.0:5173; # Use your Vite container name if using Docker
      # Essential headers for proxying standard traffic
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # CRITICAL: WebSockets support for Vite Hot Module Replacement (HMR)
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
    location /api/ {
      proxy_pass http://localhost:5000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # Remove /api from the request before passing it to the backend
      rewrite ^/api/(.*) /$1 break;
    }
  }
}
