M48
; DRILL file {KiCad 8.0.8-8.0.8-0~ubuntu24.04.1} date 2025-05-21T16:36:32-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-05-21T16:36:32-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8-8.0.8-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X7.2864Y-3.6232
X7.4774Y-3.6232
T2
X7.2746Y-3.5039
X7.4892Y-3.5039
M30
